### ISSUE TITLE
Add general text refinement job

### ISSUE THREAD

**Issue by Taekyoon** [EleutherAI/dps#1]
### Task

- [x] Filter empty or ~short text~
- [x] Deduplicate text cases
- [x] Remove general removable text patterns which are human defined by regex
- [x] Replace privacy info text patterns by tags like `<phone_number>, <credit_card_number>`

Data should be output as each categories.

**Comment by Taekyoon** [comment]
### Mask tag table

 info to replace | tag
 -- | --
 phone number | `<|tell|>`
 social security number | `<|rrn|>`
 bank account number | `<|acc|>`

**Comment by Taekyoon** [comment]
info text to replace | tag
-- | --
phone number | <\|tel\|>
social security number | <\|rrn\|>
bank account number | <\|acc\|>
credit number | <\|crd\|>
